### ISSUE TITLE
[MultiCalc] catch & find the problem while NullPointerException will be thrown

### ISSUE THREAD

**Issue by IceflowRE** [IceflowRE/javaPrimSearch#5]
java.lang.ArrayIndexOutOfBoundsException: -848
    at org.magicwerk.brownies.collections.GapList.doGet(GapList.java:465)
    at org.magicwerk.brownies.collections.BigList.doGet(BigList.java:340)
    at org.magicwerk.brownies.collections.IList.get(IList.java:174)
    at PrimeDistributor.run(PrimeCalc.java:142)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-4347-thread-8" java.lang.ArrayIndexOutOfBoundsException: -943
    at org.magicwerk.brownies.collections.GapList.doGet(GapList.java:465)
    at org.magicwerk.brownies.collections.BigList.doGet(BigList.java:340)
    at org.magicwerk.brownies.collections.IList.get(IList.java:174)
    at PrimeDistributor.run(PrimeCalc.java:142)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by IceflowRE** [comment]
No further working planned.
